### ISSUE TITLE
Add keyword `idl` to crates.io

### ISSUE THREAD

**Issue by derekdreery** [sgodwincs/webidl-rs#10]
Could you add the keyword `idl` to crates.io crate. I started rolling my own parser because I didn't know one already existed :(.

**Comment by sgodwincs** [comment]
The latest commit should fix this, thanks for the report! I think I have to push a new version for the changes to take effect on crates.io though right?

**Comment by derekdreery** [comment]
I think so, no rush though. Thanks!
