### ISSUE TITLE
2^64 -1 cannot be represented

### ISSUE THREAD

**Issue by jrakow** [sgodwincs/webidl-rs#15]
The highest `u64` value (18446744073709551615) cannot be represented with the current `Token::IntegerLiteral(i64)`.

One would probably need `SignedIntegerLiteral(i64)` as well as `UnsignedIntegerLiteral(u64)`.
Or you could use on of the 128 bit types.

**Comment by sgodwincs** [comment]
@jrakow Can you confirm the fix is what you want before I push a new version?

**Comment by sgodwincs** [comment]
Version 0.7.0 should have the fix. Thanks for the report.
