### ISSUE TITLE
Error not implemented for ParseError<usize, Token, LexicalError>

### ISSUE THREAD

**Issue by kryptan** [sgodwincs/webidl-rs#9]
`Error` trait is not implemented for the error returned from the parser. Because `Token` and `LexicalError` do not implement `Display`, the following requirements are not satisfied:

```Rust
impl<L, T, E> Error for ParseError<L, T, E> where
    L: Debug + Display,
    T: Debug + Display,
    E: Debug + Display, 
```

**Comment by sgodwincs** [comment]
Thanks for the report!

I have published a new version (v0.3.3) which should solve this issue. I also did some maintenance and updated the grammar to be aligned with the latest spec.

I'm going to close the issue for now, but if there is still a problem, feel free to reopen. Thanks!
